<?php
/**
 * @file
 */

function proxecto13_page_alter(&$page) {
  // Move search form into the footer.
  //var_dump($page);
}

/**
 *
 */ 
function proxecto13_menu() {
  // Páxina principal
  $items['proxecto13'] = array(
    'title' => 'Proxecto 13',
    'page callback' => 'proxecto13_callback',
    'file' => 'proxecto13_callback.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  $items['proxecto13-form-contorno'] = array(
    'title' => 'Modificar Contorno',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('proxecto13_form_contorno'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['proxecto13-form-usuario'] = array(
    'title' => 'Engadir Usuario',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('proxecto13_form_usuario'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['proxecto13-404'] = array(
    'title' => '404 not found',
    'page callback' => 'proxecto13_404_callback',
    'file' => 'proxecto13_40X_callback.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['proxecto13-403'] = array(
    'title' => '403 forbidden',
    'page callback' => 'proxecto13_403_callback',
    'file' => 'proxecto13_40X_callback.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  ); 
  
  return $items;
}


function proxecto13_theme($existing, $type, $theme, $path){
  return array(
    'proxecto13' => array(
        'template' => 'proxecto13',

        'variables' => array(
          'user'       => NULL,
          'acceso'     => NULL,
          'picture'    => NULL,

          'localidade' => NULL,
          'enderezo'   => NULL,
          'idade'      => NULL,
          'mobil'      => NULL,

          'site_name'   => NULL,
          'site_slogan' => NULL,

          'admin' => NULL,
          'install_profile' => NULL,
          'cron_last' => NULL,
          'cron_key' => NULL,
          'site_404' => NULL,
          'site_403' => NULL,
        ),

        'path' => drupal_get_path('module', 'proxecto13'),
     ),

     'proxecto13-404' => array(
       'template' => 'proxecto13-404',
       'variables' => array(),
       'path' => drupal_get_path('module', 'proxecto13'),
     ),

     
     'proxecto13-403' => array(
       'template' => 'proxecto13-403',
       'variables' => array(),
       'path' => drupal_get_path('module', 'proxecto13'),
     ),
  );

}

/**
 *
 */
function proxecto13_form_contorno($node, &$form_state) {
  $form['nome'] = array(
    '#title'       => t('Nome do sitio'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Nome do sitio'),    
  );
  
  $form['slogan'] = array(
    '#title'       => t('Slogan do sitio'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Slogan do sitio'),
  );
  
  $form['on404'] = array(
    '#title' => t('Activar páxina 404'),
    '#type'  => 'checkbox',    
  ); 
   
  $form['on403'] = array(
    '#title' => t('Activar páxina 403'),
    '#type'  => 'checkbox',    
  );
  
  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Enviar'),
  );
  
  return $form;
}

function proxecto13_form_contorno_submit($form, &$form_state) {
  
  variable_set('site_name',   $form_state['values']['nome']);
  variable_set('site_slogan', $form_state['values']['slogan']);

  if(!empty($form_state['values']['on404'])) {
    variable_set('site_404', 'proxecto13-404');
  } else {
    variable_set('site_404', '');
  }

  if(!empty($form_state['values']['on403'])) {
    variable_set('site_403', 'proxecto13-403');
  } else {
    variable_set('site_403', '');
  }

}

function proxecto13_form_usuario($node, &$form_state) {

  $form['user_name'] = array(
    '#title'       => t('Nome de usuario'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Nome de usuario'),    
  );

  $form['mail'] = array(
    '#title'       => t('Email'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Enderezo electrónico'),    
  );

  $form['localidade'] = array(
    '#title'       => t('Localidade'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Localidade'),    
  );

  $form['idade'] = array(
    '#title'       => t('Idade'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Idade'),    
  );

  $form['telefono'] = array(
    '#title'       => t('Teléfono'),    
    '#type'        => 'textfield',
    '#required'    => TRUE,
    '#description' => t('Teléfono'),    
  );  
  
  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Enviar'),
  );
  
  return $form;
}

function proxecto13_form_usuario_submit($form, &$form_state) {
  var_dump($form_state);die();


  require DRUPAL_ROOT.'/includes/password.inc';

  // Password por defecto
  $password = '12345';

  $account = new stdClass;
  $account->is_new = TRUE;
  $account->name = check_plain($form_state['values']['user_name']);
  $account->pass = user_hash_password($password);
  $account->mail = $form_state['values']['mail'];
  $account->init = $form_state['values']['mail'];
  $account->status = TRUE;
  $account->roles = array(DRUPAL_AUTHENTICATED_RID => TRUE);
  //$account->timezone = variable_get('date_default_timezone', '');

  user_save($account);
}

/**
 * Implements hook_form_alter().
 */
function proxecto13_form_alter(&$form, &$form_state, $form_id) {
  if('user_profile_form' == $form_id) {
    drupal_set_title('Modificación perfíl proxecto OSL');
  }
}
